import 'package:flutter/material.dart';

Map<String, Color?> colorCodeMap = {
  'A': Colors.blue,
  'B': Colors.yellow,
  'C': Colors.deepOrange,
  'D': Colors.lightGreen,
  'E': Colors.lightBlue,
  'F': Colors.amber,
  'G': Colors.pink,
  'H': Colors.cyan,
  'I': Colors.deepPurple,
  'J': Colors.brown,
  'K': Colors.indigo,
  'L': Colors.green,
  'M': Colors.blueGrey,
  'N': Colors.lime,
  'O': Colors.orange,
  'P': Colors.purple,
  'Q': Colors.teal,
  'R': Colors.blueAccent[100],
  'S': Colors.yellowAccent[100],
  'T': Colors.deepOrangeAccent[100],
  'U': Colors.lightGreenAccent[200],
  'V': Colors.lightBlueAccent[100],
  'W': Colors.amberAccent[200],
  'X': Colors.cyanAccent[100],
  'Y': Colors.deepPurpleAccent[200],
  'Z': Colors.indigoAccent[100],
};